const constants = {
    "e000": "Too Deep JSON",
    "e001": "Invalid tab/new line character found in string",
    "e002": "Illegal escape character in string",
    "e003": "Unexpected end of string",
    "e004": "Invalid use of single quotes in JSON/Array object. Use double quotes instead",
    "e005": "Numbers cannot have leading zeroes",
    "e006": "Invalid number format",
    "e007": "Invalid keyword/character",
    "e008": "Unexpected Character",
    "e009": "Unexpected tokens found after end of value",
    "e010": "Expected top level object or array",
    "e011": "Unexpected end of JSON",
    "e012": "Unexpected token found",
    "e013": "Unexpected end of JSON",
    "e014": "Unexpected end of tokens",
    "e015": "Semicolon expected",
    "e016": "Unexpected trailing comma in JSON object",
    "e017": "Expected comma or \"}\" at closing of JSON object",
    "e018": "Unexpected end of array values",
    "e019": "Unexpected end of array tokens",
    "e020": "Unexpected trailing comma in Array",
    "e021": "Expected comma or \"]\"",
}

export default constants;